apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: slot
  labels:
    k8s-app: slot
spec:
  ports:
    - port: 8000
      targetPort: 591
  selector:
    k8s-app: slot