apiVersion: apps/v1
kind: Deployment
metadata:
  name: slot
  labels:
    k8s-app: slot
    tier: backend
    env: prod
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: slot
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: slot
    spec:
      containers:
        - name: slot
          image: slot
          ports:
            - containerPort: 8000
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 410m
          memory: 512Mi