apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: payment
  labels:
    k8s-app: payment
spec:
  ports:
    - port: 4200
      targetPort: 8080
  selector:
    k8s-app: payment